version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    deploy:
      replicas: 2
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    image: toadslop/yama-quest
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_IP=${DB_IP}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      