version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env

  mongo:
    image: mongo:5.0.0-rc1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=toadslop
      - MONGO_INITDB_ROOT_PASSWORD=supersecret
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
