version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  node-app:
    build: .
    image: toadslop/yama-quest
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.0-rc1
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis:6.2.4

volumes:
  mongo-db:
