version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.0-rc1
    environment:
      - MONGO_INITDB_ROOT_USERNAME={DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD={DB_PASS}
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis:6.2.4

volumes:
  mongo-db:
