version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_IP=${DB_IP}
      - DB_PORT=${DB_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
    command: yarn dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
