### GET WHATEVER
GET http://3.101.88.163/api

### GET POSTS
GET http://3.101.88.163/api/v1/posts

### CREATE A POST
POST http://3.101.88.163/api/v1/posts
content-type: application/json

{
    "title": "SUP",
    "body": "The sup post."
}

### UPDATE A POST
PATCH http://3.101.88.163/api/v1/posts/60cdbeb8c08bbe015fdda325
content-type: application/json

{
    "title": "The Post UPDATED AGAIN",
    "body": "This is a post."
}

### GET A POST
GET http://3.101.88.163/api/v1/posts/60e2f0722537a9c0bfd4f6ad
content-type: application/json

### DELETE A POST
DELETE http://3.101.88.163/api/v1/posts/60cdbeb8c08bbe015fdda325
content-type: application/json
