### CREATE A USER
POST http://ec2-54-151-101-49.us-west-1.compute.amazonaws.com/api/v1/users/signup
content-type: application/json

{
    "username": "monkeyboy1",
    "userpass": "secret"
}

### LOGIN
POST http://localhost:3000/api/v1/users/login
content-type: application/json

{
    "username": "monkeyboy1",
    "userpass": "secret"
}