### CREATE A USER
POST http://3.101.88.163/api/v1/users/signup
content-type: application/json

{
    "username": "monkeyboy2",
    "userpass": "secret"
}

### LOGIN
POST http://3.101.88.163/api/v1/users/login
content-type: application/json

{
    "username": "monkeyboy2",
    "userpass": "secret"
}