### CREATE A USER
POST http://54.176.145.129:80/api/v1/users/signup
content-type: application/json

{
    "username": "monkeyboy1",
    "userpass": "secret"
}

### LOGIN
POST http://localhost:3000/api/v1/users/login
content-type: application/json

{
    "username": "monkeyboy1",
    "userpass": "secret"
}