### GET WHATEVER
GET http://localhost:3000/api

### GET POSTS
GET http://localhost:3000/api/v1/posts

### CREATE A POST
POST http://localhost:3000/api/v1/posts
content-type: application/json

{
    "title": "The Post12345",
    "body": "This is a post."
}

### UPDATE A POST
PATCH http://localhost:3000/api/v1/posts/60f275f510c09e024ce96209
content-type: application/json

{
    "title": "Zigga ya",
    "body": "This is a post."
}

### GET A POST
GET http://localhost:3000/api/v1/posts/60f275f510c09e024ce96209
content-type: application/json

### DELETE A POST
DELETE http://localhost:3000/api/v1/posts/60f275f510c09e024ce96209
content-type: application/json
